# permissions for end users to edit fleets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fleet-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zcontroller
    app.kubernetes.io/part-of: zcontroller
    app.kubernetes.io/managed-by: kustomize
  name: fleet-editor-role
rules:
- apiGroups:
  - junos.zach.fi
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - junos.zach.fi
  resources:
  - fleets/status
  verbs:
  - get
