---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - junos.zach.fi
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - junos.zach.fi
  resources:
  - fleets/finalizers
  verbs:
  - update
- apiGroups:
  - junos.zach.fi
  resources:
  - fleets/status
  verbs:
  - get
  - patch
  - update
