apiVersion: junos.zach.fi/v1
kind: Fleet
metadata:
  labels:
    app.kubernetes.io/name: fleet
    app.kubernetes.io/instance: fleet-sample
    app.kubernetes.io/part-of: zcontroller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zcontroller
  name: fleet-sample
spec:
  # TODO(user): Add fields here
